# config/packages/knp_paginator.yaml
knp_paginator:
  page_range: 5                      # nombre de pages à afficher dans le menu de navigation
  default_options:
    page_name: page                # nom du paramètre de la page
    sort_field_name: sort          # nom du paramètre du champ de tri
    sort_direction_name: direction # nom du paramètre de la direction du tri
    distinct: true                 # obtenir des résultats distincts, true par défaut
  template:
    #    @KnpPaginator/Pagination/sliding.html.twig
   pagination: 'partials/pagination.html.twig'  # chemin vers le template de pagination
#    sortable: '@KnpPaginator/Pagination/sortable_link.html.twig' # chemin vers le template des liens triables