controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing-sf4.xml"

#fos_js_routing:
#    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing-sf4.xml"

_security_logout:
    resource: security.route_loader.logout
    type: service
    methods: ['POST', 'GET']

maintenance_page:
    path: /maintenance
    controller: App\Controller\DefaultController::maintenancePage
